### ISSUE TITLE
Instructions on Database configurations needed.

### ISSUE THREAD

**Issue by WanNJ** [nonocast/todolist#2]
I'm using Mac to run this app:
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

If instructions on how to set up the database are added, it would be perfect. Thank you!

**Comment by nonocast** [comment]
https://github.com/nonocast/todolist/tree/master/src/main/resources/db
